[package]
name = "boggle"
version = "0.1.0"
authors = ["Ben Batha <bhbatha@gmail.com>"]
edition = "2018"

[dependencies]
rayon = "^1.1"
typed-arena = "^1.2"
smallvec = "^0.6"

[features]
unstable = []

[profile.bench]
debug = true