[package]
name = "boggle"
version = "0.1.0"
authors = ["Ben Batha <bhbatha@gmail.com>"]

[dependencies]
rayon = "^0.8"
typed-arena = "^1.2"
smallvec = "^0.4"

[features]
unstable = []

[profile.bench]
debug = true